export default[
    {
        id:1,
        name:"Appliances",
        img:"./assets/Appliances.jpg"
    },
    {
        id:2,
        name:"Audio",
        img:"./assets/Audio.jpg"
    },
    {
        id:3,
        name:"Beauty",
        img:"./assets/Beauty.jpg"
    },
    {
        id:4,
        name:"Electronics",
        img:"./assets/Electronics.jpg"
    },
    {
        id:5,
        name:"Footwear",
        img:"./assets/Footwear.jpg"
    },
    {
        id:6,
        name:"MensWear",
        img:"./assets/MensWear.jpg"
    },
    {
        id:7,
        name:"SmartPhones",
        img:"./assets/SmartPhones.jpg"
    },
    {
        id:8,
        name:"WeatSide",
        img:"./assets/WestSide.jpg"
    },
    {
        id:9,
        name:"WomensWear",
        img:"./assets/WomensWear.jpg"
    }
    ]